// Copy to config.js and fill in your Supabase credentials for local dev.
// On Vercel, config.js is auto-generated by scripts/build_web_config.py at build time.
window.APP_CONFIG = {
  supabaseUrl: "",
  supabaseAnonKey: "",
};
